# These are supported funding model platforms

github: [SLinBox]
patreon:
open_collective: SLinBox
ko_fi: SLinBox
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: SLinBox
thanks_dev:
custom: []
